apiVersion: v1
kind: Secret
metadata:
  name: workshop-ssh-key
type: Opaque
stringData:
  key: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdrq8QOVo8CzPrgKPC4MXN+Vn6dWdZksAWQVUrC6jvcjuFKQgb8EiMAxS0djFJKbk14SL6BRuUwBopjkumxD6kS38VDvGNlEIcWG2sQKnAzEtGdzG4N72qu6ObNK+ralg8Gu5uZPhziyKFXpwg9kOBl1qxOiycR4acyaDt4SxSAD7BWJPEbiYUeCrcZQ+BMrVUwLPpLYBa+h0/uJmK4+U632MfYUMiudNXLcs3e3f/yi5GMli6BcGgl7wlEbgnUZQzrW0D04jNWk0/JGU506c166b6Dy6bigefUlLvjJ4I/8vZns3ZRj3YV6oPaZMY9BZ9FrB0jE+7XgVXlMY7lyXX
