apiVersion: v1
kind: Secret
metadata:
  name: workshop-ssh-key
type: Opaque
stringData:
  key: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB1r3VGE6kzC+nx/JZ4W3LBTtZt1bgoSFZJis9K1ignJ openshift-gitops-workshop
